services:
  - type: web
    name: django
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: gunicorn webhook.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - fromGroup: webhook-env

  - type: worker
    name: celery-worker
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: celery -A webhook worker --loglevel=info
    envVars:
      - fromGroup: webhook-env

  - type: worker
    name: celery-beat
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: celery -A webhook beat --loglevel=info
    envVars:
      - fromGroup: webhook-env

  - type: redis
    name: redis
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all (for dev/testing)
