services:
  - type: web
    name: django
    env: docker
    repo: https://github.com/yourusername/yourrepo
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - fromGroup: django-env
    ports:
      - 8000
    plan: free
    healthCheckPath: /
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all IPs

  - type: worker
    name: celery
    env: docker
    repo: https://github.com/yourusername/yourrepo
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - fromGroup: django-env

  - type: worker
    name: celery-beat
    env: docker
    repo: https://github.com/yourusername/yourrepo
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - fromGroup: django-env

  - type: redis
    name: redis
    region: oregon
    plan: free
