# Generated by Django 5.2 on 2025-04-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('target_url', models.URLField()),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
