# Generated by Django 5.2 on 2025-04-25 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_identifier', models.CharField(max_length=255)),
                ('target_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('attempt_number', models.PositiveIntegerField()),
                ('outcome', models.CharField(max_length=50)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscription')),
            ],
        ),
    ]
